name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      - uses: pre-commit/action@v3.0.0

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      - name: Upgrade pip
        run: python -m pip install -U pip setuptools wheel
      - name: Install dependencies
        run: |
          pip install .[statsmodels,prophet,sktime]
          pip install pytest
      - name: Run tests
        run: pytest -m "not tfp"

  test-tfp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      - name: Upgrade pip
        run: python -m pip install -U pip setuptools wheel
      - name: Install TensorFlow Probability extra
        run: |
          pip install .[tfp]
          pip install pytest
      - name: Run tfp tests
        run: pytest -m tfp
